# Generated by Django 4.2.5 on 2023-09-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_task_requester_task_watcher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Task1',
        ),
    ]
