# Generated by Django 4.2.5 on 2023-09-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_rename_task_task1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task1',
            new_name='Task',
        ),
    ]
