# Generated by Django 4.2.5 on 2023-09-25 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_rename_task1_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='watcher',
            field=models.ManyToManyField(related_name='watcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
