# Generated by Django 4.2.5 on 2023-09-25 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_task_assigned_to_alter_task_watcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
