# Generated by Django 4.2.5 on 2023-09-27 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_user_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='soft_skill',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='watcher',
            field=models.ManyToManyField(blank=True, null=True, related_name='watcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
