# Generated by Django 4.2.5 on 2023-09-29 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.BigIntegerField(blank=True, choices=[('SA', 'Software Analyst'), ('SD', 'Software Designer'), ('SP', 'Software Programmer'), ('ST', 'Software Tester'), ('SM', 'Software Maintainer')], null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
