# Generated by Django 4.2.5 on 2023-09-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(blank=True, choices=[('SA', 'Software Analyst'), ('SD', 'Software Designer'), ('SP', 'Software Programmer'), ('ST', 'Software Tester'), ('SM', 'Software Maintainer')], max_length=5, null=True),
        ),
    ]
