# Generated by Django 4.2.5 on 2023-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0014_alter_role_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
