# Generated by Django 4.2.5 on 2023-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0015_role_is_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
