# Generated by Django 4.2.5 on 2023-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0019_ticket_remove_notification_task_delete_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
    ]
