# Generated by Django 4.2.5 on 2023-10-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0022_remove_notification_user_notification_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtiresult',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
